language: python
dist: xenial
python:
- 3.7



before_script: # code coverage tool
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
   - ./cc-test-reporter before-build

script: pytest --cov=test_app --cov-report xml --cov-report term



after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
